version: '3'
services:
  api:
    image: slack-api
    build: .
    env_file:
    - .env
    ports:
     - "3001:3000"
    volumes:
     - ./:/api/
     - /api/node_modules
    command: ['yarn', 'start']